services:
  mongoserver:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017" # doesnt actually need to be exposed, just for mongosh or whatever
    volumes:
      - mongodb_external:/data/db
  webserver:
    build: .
    restart: always
    ports:
      - "2763:2763"
    depends_on:
      - mongoserver
    environment:
      - MONGO_URL=mongodb://mongoserver:27017/

volumes:
  mongodb_external:
    external: true