services:
  mongoserver:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_external:/data/db
  webserver:
    build: .
    restart: always
    ports:
      - 2763:2763
    depends_on:
      - mongoserver
    environment:
      - MONGO_URL=mongodb://mongoserver:27017/
    volumes:
      - gallery_uploads:/doeball-ca/public/assets/uploads
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --token ${TUNNEL_SECRET}
    # create a .env file, with TUNNEL_SECRET=13246hj34jn4g36thkj2354gvyhjt2g45bv3htj453gvt6j34
    network_mode: "host"

volumes:
  mongodb_external:
  gallery_uploads:
    external: true
